Numpy is a package in python used to create single and multi-dimentional array.
Numpy contains large libraries of mathematical functions like linear algebra functions and Fourier transforms.
Numpy's array class is known as ndarray.


In [7]:
#Method-1 -----Single dimentional array
import numpy as np
arr=np.array([10,20,89,45])
print(arr)

[10 20 89 45]


In [8]:
#Method-2
from numpy import *
arr=array([10,20,54,89])
print(arr)

[10 20 54 89]


We can create array in numpy several ways.They are:
1. using array() function
2. using linspace() function
3. using logspace() function
4. using arange() function
5. using zeroes() and ones() function

In [9]:
#Using array()
from numpy import *
arr=array([10,20,45,67])
print(arr)

[10 20 45 67]


In [10]:
#Using linspace()
from numpy import *
arr=linspace(32,62,15)
print(arr)

[32.         34.14285714 36.28571429 38.42857143 40.57142857 42.71428571
 44.85714286 47.         49.14285714 51.28571429 53.42857143 55.57142857
 57.71428571 59.85714286 62.        ]


In [11]:
#Using logspace()
from numpy import *
arr=logspace(1,10,3)
print(arr)

[1.00000000e+01 3.16227766e+05 1.00000000e+10]


In [12]:
#Using arange()
from numpy import *
arr=arange(65,100,5)
print(arr)

[65 70 75 80 85 90 95]


In [13]:
#USing zeroes() and ones()-----create array with all zero or one elements
from numpy import *
arr=zeros(9)
arr2=ones(7)
arr3=ones((2,3))
arr4=full((2,4),5)
arr5=eye(3,3) #identity matrix
print(arr)
print(arr2)
print(arr3)
print(arr4) 
print(arr5)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Mathematical Operations on arrays:
1.Arthmetic Operations

In [14]:
arr=array([10,20,30,40,50])
arr2=([5,10,15,20,25])
print(arr,arr2,sep="        ")
print("updated array1 : ",arr+10)
print("arr+(-,*,/,%)arr2", arr+arr2)
print("Expression value: ",(arr+5)**2-10)
print("sine(cose,tan,arcsin,arcs,arctan) value",sin(arr))
print(sqrt(arr2))
print(power(arr,2))
print("original arr and arr2 : ",arr,arr2,sep="   " )


[10 20 30 40 50]        [5, 10, 15, 20, 25]
updated array1 :  [20 30 40 50 60]
arr+(-,*,/,%)arr2 [15 30 45 60 75]
Expression value:  [ 215  615 1215 2015 3015]
sine(cose,tan,arcsin,arcs,arctan) value [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[2.23606798 3.16227766 3.87298335 4.47213595 5.        ]
[ 100  400  900 1600 2500]
original arr and arr2 :    [10 20 30 40 50]   [5, 10, 15, 20, 25]


2.Relational Operations on array

In [15]:
print(arr>arr2)
print(arr<arr2)
c=arr==arr2
print("to check if any element is true: ",any(c))
print("to check if all elements is true",all(c))

[ True  True  True  True  True]
[False False False False False]
to check if any element is true:  False
to check if all elements is true False


3.Logical operations on array---logical_and(),logical_or(),logical_not()

In [16]:
print(arr)
print(logical_or(arr>8,arr<90))
print(logical_and(arr>8,arr<90))
print(logical_not(arr))

[10 20 30 40 50]
[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


Some methods used in array:

1. where() function --can be used to create a new arr based on whether the given condition is True or False.
syntax-where(cond,exp1,exp2)

In [17]:
print(arr)
print(arr2)
print(where(arr>arr2,arr,arr2))

[10 20 30 40 50]
[5, 10, 15, 20, 25]
[10 20 30 40 50]


2. nonzero() function-returns an arr that contains the indexes of the elements of the array which are non zero.
syntax-nonzero(array)

In [18]:
arr3=array([1,5,-2,0,3,4,5,0,100])
print("ORiginal arr: ",arr3)
c=nonzero(arr3)
for i in c:
    print("indexes of non zero elemnt",i)
print("non zero elements are: ",arr3[c])    

ORiginal arr:  [  1   5  -2   0   3   4   5   0 100]
indexes of non zero elemnt [0 1 2 4 5 6 8]
non zero elements are:  [  1   5  -2   3   4   5 100]


Aliasing the arrays - Aliasing is not copying .It means giving another name to the existiong object and vice versa.
syntax--b=a
--->In Aliasing, memory is not located to array b
--->a and b both reference to the object i.e array

In [19]:
a=arange(1,6)
b=a
print("ORiginal arr: ",a)
print("Aliasing array: ",b)
b[0]=99
print("Now,Original arr: ",a)
print("Aliasing arr",b)


ORiginal arr:  [1 2 3 4 5]
Aliasing array:  [1 2 3 4 5]
Now,Original arr:  [99  2  3  4  5]
Aliasing arr [99  2  3  4  5]


3. View() and copy() function:
view(): Itis used for "shallow copying".
        Syntax--b=a.view()
        The memory is allocated to the array b
        The modifications done in array b will also modified array a.


copy(): It is used for "deep copying".
        when modifications done on array b doesnot affect array a.

In [20]:
#View() Function
a=arange(1,5)
b=a.view()
b[0]=99
print(a,b,sep="       ")
#Copy() Function
p=arange(5,10)
q=p.copy()
q[0]=56
print(p,q,sep="     ")


[99  2  3  4]       [99  2  3  4]
[5 6 7 8 9]     [56  6  7  8  9]


4. reshape() method :It is used to change the shape of an array.
                     The new array must have same number of elements as in the original array.

In [21]:
arr1=arange(1,13)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
arr1=arr1.reshape(3,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr1=arr1.reshape(6,2)
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

5.Flatten() Method : It is useful to return a copy of the array collapsed in one dimension.

In [24]:
arr2=arr1.flatten()
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Slicing in an Array

In [25]:
a=arange(10,16)
print(a)
print(a[1:6:2])
print(a[::])
print(a[-2:2:-1])
print(a[:-2:])

[10 11 12 13 14 15]
[11 13 15]
[10 11 12 13 14 15]
[14 13]
[10 11 12 13]


Attributes of an array


1. ndim Attribute: returns the dimensions of an array.

In [26]:
a=array([1,2,3])
b=array([[1,2,3],[4,5,6],[7,8,9]])
c=array([[[1,2,3],[4,5,6]],[[4,5,6],[6,7,8]]])
print(ndim(a))
print(ndim(b))
print(ndim(c))

1
2
3


2. shape Attribute: gives the no. of elements along each dimension and we can also change the shape of an array.

In [27]:
print(b.shape)
print(c.shape)

(3, 3)
(2, 2, 3)


In [28]:
print("Original array: ",c)
c.shape=(3,2,2)
print("New array",c)

Original array:  [[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [6 7 8]]]
New array [[[1 2]
  [3 4]]

 [[5 6]
  [4 5]]

 [[6 6]
  [7 8]]]


3. size attribute- gives the total number of elements in the array.

In [29]:
print(a.size)

3


4. itemsize - it gives the memory size of the array elements in bytes.

In [30]:
print("int: ",a.itemsize)
p=array([2.0,8.0,4.0])
print("float: ",p.itemsize)

int:  4
float:  8


5. dtype Attribute- gives the datatype of the elements in the array.

In [31]:
print(p.dtype)
print(a.dtype)

float64
int32


5.nbytes-gives the total no.of bytes occupied in an array. 
         The total number of bytes = size of an array*item size of each element in the array.

In [32]:
print(a.nbytes)

12


Working with multi-Dimentional Array

We can create multi-Dimentional array in the following ways:



1.  Using array() function
2. Using ones() and zeroes() function
3. Using eye() function
4. Using reshape() function

1. The array() Function

In [33]:
a=array([[[1,2,3,4]],[[5,6,7,8]],[[3,6,9,6]]])
print(a)
a.ndim

[[[1 2 3 4]]

 [[5 6 7 8]]

 [[3 6 9 6]]]


3

2. The ones() and zeroes() function

In [34]:
arr=ones((2,3))
arr2=zeros((4,3,4))
print(arr)
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


3. The eye() function: IT creates a 2D array with diagonal elements as 1.
Syntax is: eye(n,dtype=datatype)

In [35]:
a=eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. The reshape() function: This function is useful to comvert a 1D array into multidimentional array.
Syntax is:  reshape(array_name,(n,r,c))

In [36]:
arr=array([1,2,3,4,5,6,7,8,9,10,11,12])
print(reshape(arr,(6,2)))
print("\n")
print(reshape(arr,(2,3,2)))


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


Indexing in Multidimentional array

In [37]:
#2D array
arr=[[1,2,3],[5,6,7],[8,9,3]]
#display only rows
for i in range(len(arr)):
    print(f"row:{i} and elements are: {arr[i]}")
#display only columns
for i in range(len(arr)):
    for j in range(len(arr[i])):
        print(arr[i][j], end=" ")

row:0 and elements are: [1, 2, 3]
row:1 and elements are: [5, 6, 7]
row:2 and elements are: [8, 9, 3]
1 2 3 5 6 7 8 9 3 

In [38]:
#3D array
arr=array([[[1,2,3],[3,4,5]],[[4,5,6],[6,7,8]],[[7,8,9],[5,4,3]]])
for i in range(len(arr)):
    print(f"row: {i} and alements are: {arr[i]}")
for i in range(len(arr)):    
    for j in range(len(arr[i])):
        print(f"row with column{j}: {arr[i][j]}")
for i in range(len(arr)):
    for j in range(len(arr[i])):
        for k in range(len(arr[i][j])):
            print(arr[i][j][k],end="\t")
        print()
    print()    
               

row: 0 and alements are: [[1 2 3]
 [3 4 5]]
row: 1 and alements are: [[4 5 6]
 [6 7 8]]
row: 2 and alements are: [[7 8 9]
 [5 4 3]]
row with column0: [1 2 3]
row with column1: [3 4 5]
row with column0: [4 5 6]
row with column1: [6 7 8]
row with column0: [7 8 9]
row with column1: [5 4 3]
1	2	3	
3	4	5	

4	5	6	
6	7	8	

7	8	9	
5	4	3	



Slicing :


In [39]:
arr=array([[[1,2,3],[3,4,5]],[[4,5,6],[6,7,8]],[[7,8,9],[5,4,3]]])
print(arr[0:2,1:3])

[[[3 4 5]]

 [[6 7 8]]]


Fancy Indexing:Select multiple elements at once

In [40]:
arr=array([10,20,30,40,50])
print(arr[[0,2,4]])


[10 30 50]


Boolean MAsking:filtering the data based on conditions.

In [41]:
arr=array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


Matrices in numpy: Numpy offers a special object called matrix.
   Syntax: matrix_name=matrix(2D array or string)


In [42]:
#matrix using array
a=matrix(arange(1,11).reshape(2,5))
print(a)
#matrix using string
str='1 2 4;3 4 6;5 6 8'
b= matrix(str)
print(b)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 4]
 [3 4 6]
 [5 6 8]]


Diagonal elements of a matrix

In [43]:
d=b.diagonal()
print(d)

[[1 4 8]]


Minimum and Maximum elements

In [44]:
print(a.max())
print(a.min())

10
1


Sum and Average of Elements

In [45]:
print(a.sum())
print(a.mean())

55
5.5


Product of elements: prod(0)-->returns a matrix that contains the produt of elements in each column of the matrix.  prod(1)-->returns a matrix that contaims the product of lelements in each column of the matrix.

In [46]:
m=matrix(arange(1,11).reshape(5,2))
print(m.prod(0))
print(m.prod(1))

[[ 945 3840]]
[[ 2]
 [12]
 [30]
 [56]
 [90]]


Sorting the matrix: sort() function is used that sort the matrix elements in ascending order. Syntax= sort(matrix,axis=0/1)   if axix=1--->sort all the elements row wise. if axis=0--->sort all the elements columnwise.

In [47]:
print(m)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [48]:
#row
a=matrix([[5,4,2],[5,8,3]])
print(sort(a,axis=1))
#column
print(sort(a,axis=0))

[[2 4 5]
 [3 5 8]]
[[5 4 2]
 [5 8 3]]


Transpose of a matrix: transpose() and getT()


In [49]:
print(a.transpose())
print()
print(a.getT())

[[5 5]
 [4 8]
 [2 3]]

[[5 5]
 [4 8]
 [2 3]]


In [1]:
r,c=[int(a) for a in input("Enter rows and columns: ").split()]
str=input("Enter the elements with one space between them: ")
m=matrix(str).reshape(r,c)
print(m)
print(m.transpose())

ValueError: not enough values to unpack (expected 2, got 0)

Matrix addition,substraction and division

In [ ]:
m1=matrix([1,2,3,4,5,6,7,8,9,10]).reshape(2,5)
m2=matrix([11,12,13,14,15,16,17,18,19,20]).reshape(2,5)
print("Addition: ",m1+m2)
print("substraction: ",m1-m2)
print("division: ",m1/m2)

Addition:  [[12 14 16 18 20]
 [22 24 26 28 30]]
substraction:  [[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]
division:  [[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]
 [0.375      0.41176471 0.44444444 0.47368421 0.5       ]]


Matrix Multiplication:just like mathematics

In [ ]:
m1=matrix([1,2,3,4,5,6,7,8,9,10]).reshape(2,5)
m2=matrix([11,12,13,14,15,16,17,18,19,20]).reshape(5,2)
print(m1)
print()
print(m2)
print()
print(m1*m2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

[[245 260]
 [620 660]]


1. Random numbers: Numpy has a sub module named random that is equipped with the rand() function. 
2. It will generate random numbers between 0.0 and 1.0

In [ ]:
#1D array
a=random.rand(5)
print(a)
#2D array
b=random.rand(3,5)
print(b)

[0.21755753 0.2617409  0.58362538 0.04015475 0.87297605]
[[0.4368997  0.89153835 0.25682566 0.19331235 0.28300962]
 [0.28600856 0.20283404 0.42425705 0.27687596 0.78158914]
 [0.94133748 0.68694467 0.24851388 0.40372243 0.34802173]]


## Handling missing data
1.np.isnan()===detect missing values--always return boolean value(true/false)
# we can not compare two nan values
2.np.nan_to_num()===not a number to number conversion
3.no.isinf===detect infinity

In [ ]:
import numpy as np
arr=np.array([1,nan,3,nan,5])
print(np.isnan(arr))
#print(np.nan_to_num(arr,nan=100))
print(np.nan_to_num(arr))

[False  True False  True False]
[1. 0. 3. 0. 5.]


In [ ]:
import numpy as np
arr=np.array([1,np.inf,3,-np.inf,5])
print(np.isinf(arr))
cleaned_arr=np.nan_to_num(arr,posinf=100,neginf=-100)
print(cleaned_arr)

[False  True False  True False]
[   1.  100.    3. -100.    5.]
